version: "3"

services:
  app-checkout:
    environment:
      - PORT=8080
    container_name: app-checkout
    build:
      context: .
      dockerfile: Dockerfile.prod
      
    ports:
      - 3001:8080
    command: pnpm run start --filter=saleor-app-checkout...
    
  storefront:
    environment:
      - PORT=8080
    container_name: storefront
    build:
      context: .
      dockerfile: Dockerfile.prod
      
    ports:
      - 3000:8080
    command: pnpm run start --filter=storefront...
